### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by ShahrukhYousafzai** [Sarps/botjs#1]
![image](https://user-images.githubusercontent.com/52627061/96479817-e3005480-1252-11eb-82b7-f928824aeed3.png)

Please fix it... I tried on server and without server as well but it isn't working!

**Comment by jaymzway** [comment]
what fixxed everything for me was i copied everything from on server and pasted it into the nonserver then all of my errors went away and says that it is all now fully loaded but the next problem after that is you ask any questions it responds back with hi im an ai assistant here to help you. no matter what you ask the response stays the same so if someone can help figure that part out i would be really happy hope this helps you out shahrukhyousafzai let me know if that fixed your problem i spent 7 hours on that part cant figure out the rest my eyes are burnt out from looking 
![Screenshot_92](https://github.com/Sarps/botjs/assets/9672674/00b6bf86-b01c-4ce5-ae18-aef28399b74f)

**Comment by ShahrukhYousafzai** [comment]
Thanks for that. but it was literally a 3-year-old issue that I mentioned. In 2023, We've got ChatGPT and it's API, so I upgraded myself. I don't use AIML now anymore. I'll suggest you use ChatGPT API too. No headache, no eyes burning. AIML is really really really old thing unfortunately with a very few people of community now :( 

Moving to ChatGPT is a better option ig.

**Comment by jaymzway** [comment]
That's understandable but sometimes it's feeling relief that there was at
least an answer from somebody after such a long dreadful unanswered
question look like it needed to be answered I'm towing around with the old
AIML just for old time's sake and to see where I could take it to

**Comment by ShahrukhYousafzai** [comment]
True, I agree. I was surprised myself that I finally got an answer from someone. I even did forget that issue I opened. 😅

**Comment by jaymzway** [comment]
Yeah I've had that happen it was 10 years ago I asked for some help and 12
years later I get a response what are some of the AI features have you got
involved with that I could find to be resourceful
